### ISSUE TITLE
Is this repo still needed?

### ISSUE THREAD

**Issue by vantezzen** [getferdi/franz#5]
@kytwb Is this repository still needed? We haven't been using it but instead directly pulling Franz into Ferdi instead.

**Comment by kytwb** [comment]
Wasn't the purpose of this repository for us to have Franz/Ferdi sync done automatically? I see the pull requests on this repository are up-to-date with Franz master; next time Franz has an update on master, it should update this repository with a new pull request, which once merged, should then sync automatically with getferdi/ferdi, no? I think it was set so we don't have to keep checking Franz for us to stay in sync with it manually. I don't remember seeing a pull request from this repository to getferdi/ferdi though. Maybe we want to fix this instead of deprecating and going back to a manual sync?

**Comment by vantezzen** [comment]
With the last update of Franz (5.4.0 I think?) there were many merge conflicts and we also needed to remove many paywall features so the automatic merging didn't really do anything.

So I ran `git merge http://github.com/meetfranz/franz.git` instead and fixed the merge conflicts and paywall problems locally. I think Ferdi is too different from Franz now for us to just automatically sync - also Franz updates are really not that frequent.

WDYT?

**Comment by kytwb** [comment]
I'm still to keep things automated for the prosperity of the project, especially since we're lacking documentation on the processes for now if someone else was to take over. Were the merge conflicts the same with the automated process and the manual process? If yes, we should be able to fix them in the pull request made?

I understand there's going to be more and more merge conflicts, but having the process automated is still a good to have imo.

**Comment by vantezzen** [comment]
Good point. I think we should keep this repo then but make sure the automatic PRs work when Franz gets an update.
